### ISSUE TITLE
I want to give a talk

### ISSUE THREAD

**Issue by joseluiscadena** [GDGAndroidtitlan/Meetup-AndroidNights#2]
Hello, I'm Jose Luis Cadena from segundamano.mx, many of my colleagues have talked about many interesting topics, i want to expose some other's one. Now, i do not have the final topic, but if it is possible, schedule a talk given by me, thanks.

By the way, I could not add a blue label to this issue, maybe some permissions?

**Comment by erikjhordan-rey** [comment]
@josephdev89 Thank you for your interest we will soon get in touch with you, could you send us your a mail gdgandroidatitlan@gmail.com, please?

**Comment by joseluiscadena** [comment]
@erikcaffrey  joseluis.cadena@segundamano.mx I will be aware of notices. Thanks
