### ISSUE TITLE
Creando interfaces con anko

### ISSUE THREAD

**Issue by gorrotowi** [GDGAndroidtitlan/Meetup-AndroidNights#4]
#2 En esta charla hablare sobre Anko, la librería DLS hecha por JetBrains en Kotlin para crear interfaces. Así como explicare las ventajas que tiene sobre XML

**Comment by erikjhordan-rey** [comment]
@gorrotowi te gustaría participar en este meetup es mañana o hasta el siguiente ???

**Comment by gorrotowi** [comment]
@erikcaffrey Para luego es tarde no? ;)

**Comment by erikjhordan-rey** [comment]
@gorrotowi Es mañana a las  7 pm si estás seguro de llegar a tiempo te damos un espacio pero si no mejor el siguiente meetup como tú veas, que dices?

**Comment by gorrotowi** [comment]
@erikcaffrey ya hasta estoy preparando las diapositivas y los ejemplos 😄

**Comment by erikjhordan-rey** [comment]
@gorrotowi pásame tu email y mañana te vemos en el evento. Gracias por el apoyo!

**Comment by gorrotowi** [comment]
@erikcaffrey sebastian.tellez.o@gmail.com

**Comment by erikjhordan-rey** [comment]
@gorrotowi Te he enviado un mail Saludos!
